env:
  global:
    - CONAN_REFERENCE="Catch/1.9.3"
    - CONAN_USERNAME="uilianries"
    - CONAN_CHANNEL="ci"
    - CONAN_STABLE_BRANCH_PATTERN="release/*"
    - CONAN_UPLOAD="https://api.bintray.com/conan/uilianries/conan"

linux-job: &linux-job
    os: linux
    sudo: required
    language: python
    services:
      - docker
    python: "3.6"

osx-job: &osx-job
    os: osx
    language: generic

matrix:
    include:

    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=4.1 CONAN_DOCKER_IMAGE=uilianries/conangcc41 CONAN_ARCHS=x86_64
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_CLANG_VERSIONS=3.8 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_USE_DOCKER=1
    - <<: *linux-job
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_USE_DOCKER=1
    - <<: *osx-job
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3
    - <<: *osx-job
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0
    - <<: *osx-job
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
