build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: "https://api.bintray.com/conan/uilianries/conan"
    CONAN_REFERENCE: "Catch/1.9.4"
    CONAN_USERNAME: "uilianries"
    CONAN_CHANNEL: "ci"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - MINGW_CONFIGURATIONS: "6.2@x86_64@seh@posix,6.2@x86_64@sjlj@posix"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install --upgrade conan
  - pip.exe install --upgrade conan_package_tools
  - conan user

test_script:
  - python build.py
